export const PJTD_LIST = [
  {
    prop: "index",
    label: "序号",
    width: 100,
    fixed: "left",
    align: "center",
  },
  {
    prop: "year",
    label: "年",
    width: 100,
    align: "center",
  },
  {
    prop: "month",
    label: "月",
    width: 100,
    align: "center",
  },
  {
    prop: "projectName",
    label: "项目名称",
    minWidth: 50,
    width: 200,
    fixed: "left",
    align: "center",
  },
  {
    prop: "projectCode",
    label: "项目编码",
    minWidth: 50,
    align: "center",
  },
  {
    prop: 'parentProjectName',
    label: "父项目名称",
    minWidth: 50,
    align: "center",
  },
  {
    prop: "parentProjectCode",
    label: "父项目编码",
    minWidth: 50,
    fixed: "left",
    align: "center",
  },
  {
    prop: "money",
    label: "收入金额",
    minWidth: 50,
    align: "center",
  },
];

export const ALREADY_BILLING = [
  {
    prop: "index",
    label: "序号",
    width: 100,
    fixed: "left",
    align: "center",
  },
  {
    prop: "year",
    label: "年",
    width: 100,
    align: "center",
  },
  {
    prop: "month",
    label: "月",
    width: 100,
    align: "center",
  },
  {
    prop: "projectName",
    label: "项目名称",
    minWidth: 50,
    fixed: "left",
    align: "center",
  },
  {
    prop: "projectCode",
    label: "项目编码",
    minWidth: 50,
    align: "center",
  },
  {
    prop: 'parentProjectName',
    label: "父项目名称",
    minWidth: 50,
    align: "center",
  },
  {
    prop: "parentProjectCode",
    label: "父项目编码",
    minWidth: 50,
    fixed: "left",
    align: "center",
  },
  {
    prop: "money",
    label: "开票金额",
    width: 160,
    align: "center",
  },
  {
    prop: "invoiceDate",
    label: "开票日期",
    width: 160,
    align: "center",
  },
  {
    prop: "chargeInvoiceCurrency",
    label: "币种",
    width: 160,
    align: "center",
  },
];

export const RECEIPTS_MONEY = [
  {
    prop: "index",
    label: "序号",
    width: 100,
    fixed: "left",
    align: "center",
  },
  {
    prop: "year",
    label: "年",
    width: 100,
    align: "center",
  },
  {
    prop: "month",
    label: "月",
    width: 100,
    align: "center",
  },
  {
    prop: "projectName",
    label: "项目名称",
    minWidth: 50,
    fixed: "left",
    align: "center",
  },
  {
    prop: "projectCode",
    label: "项目编码",
    minWidth: 50,
    align: "center",
  },
  {
    prop: 'parentProjectName',
    label: "父项目名称",
    minWidth: 50,
    align: "center",
  },
  {
    prop: "parentProjectCode",
    label: "父项目编码",
    minWidth: 50,
    fixed: "left",
    align: "center",
  },
  {
    prop: "money",
    label: "收款金额",
    width: 160,
    align: "center",
  },
  {
    prop: "chargeReceiveCurrency",
    label: "币种",
    minWidth: 50,
    align: "center",
  },
  {
    prop: "bankArrivalDate",
    label: "银行到账日期",
    width: 160,
    align: "center",
  },
  {
    prop: "processCompleteDate",
    label: "认领完成日期",
    width: 160,
    align: "center",
  },
];